# Generated by Django 4.0.6 on 2022-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='short_desc',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
