# Generated by Django 4.0.6 on 2022-08-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_logs_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
