# Generated by Django 4.0.6 on 2022-08-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_logs_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='short_desc',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.CharField(default='2022-08-08 00:05:01', max_length=50),
        ),
    ]
