# Generated by Django 4.0.6 on 2022-08-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_logs_short_desc_alter_logs_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.CharField(default='2022-08-08 05:44:08.081288', max_length=50),
        ),
    ]
