# Generated by Django 4.0.6 on 2022-08-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_logs_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.CharField(default='2022-08-08 05:50:48', max_length=50),
        ),
    ]
