# Generated by Django 4.0.6 on 2022-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default='None', upload_to='pics'),
        ),
    ]
