# Generated by Django 4.0.6 on 2022-08-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_remove_logs_img_image_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
