# Generated by Django 4.0.6 on 2022-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='isInternal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
