# Generated by Django 4.0.6 on 2022-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0002_media_isinternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='timestamp',
            field=models.DateField(default='2022-07-22'),
        ),
    ]
