# Generated by Django 4.0.6 on 2022-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0003_media_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='isInternal',
            field=models.BooleanField(default=False),
        ),
    ]
