# Generated by Django 4.0.6 on 2022-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0005_alter_media_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.DateField(default='2022-07-22'),
        ),
    ]
