# Generated by Django 4.0.6 on 2022-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
