# Generated by Django 4.0.6 on 2022-08-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0010_alter_media_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField()),
                ('parentKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reiserx.changelog')),
            ],
        ),
    ]
