# Generated by Django 4.0.6 on 2022-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0012_alter_changelogdata_parentkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='version',
            field=models.FloatField(default=0.0),
        ),
    ]
