# Generated by Django 4.0.6 on 2022-08-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0013_changelog_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelogdata',
            old_name='parentKey',
            new_name='changelog',
        ),
    ]
