# Generated by Django 4.0.6 on 2022-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0014_rename_parentkey_changelogdata_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogdata',
            name='logs',
            field=models.CharField(max_length=300),
        ),
    ]
