# Generated by Django 4.0.6 on 2022-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0015_alter_changelogdata_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogdata',
            name='logs',
            field=models.CharField(max_length=200),
        ),
    ]
