# Generated by Django 4.0.6 on 2022-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0016_alter_changelogdata_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.FloatField(),
        ),
    ]
