# Generated by Django 4.0.6 on 2022-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiserx', '0017_alter_changelog_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDownloadUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
