# Generated by Django 4.1.7 on 2023-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reiserx", "0018_driverdownloadurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=70)),
                ("message", models.TextField()),
            ],
        ),
    ]
