# Generated by Django 4.1.7 on 2023-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reiserx", "0019_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, max_length=50),
        ),
    ]
