# Generated by Django 4.2.2 on 2023-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reiserx", "0020_contact_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverDownloadUrl",
        ),
    ]
