# Generated by Django 4.1.7 on 2023-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
