# Generated by Django 4.1.7 on 2023-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_comment_email_comment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="main.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
