# Generated by Django 4.1.7 on 2023-05-03 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=None, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
