# Generated by Django 4.1.7 on 2023-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_category_image_alter_post_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=70)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now=True, max_length=50)),
            ],
        ),
    ]
