# Generated by Django 4.1.7 on 2023-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_post_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
