# Generated by Django 4.2.1 on 2023-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_subscriber_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
