# Generated by Django 4.2.1 on 2023-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_contact_email_alter_tag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_ad",
            field=models.BooleanField(default=False),
        ),
    ]
