# Generated by Django 4.2.2 on 2023-09-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("translated_title", models.CharField(max_length=200)),
                ("translated_description", models.CharField(max_length=255)),
                ("translated_content", models.TextField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translated_version",
                        to="main.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "language_code")},
            },
        ),
    ]
