# Generated by Django 4.2.2 on 2023-09-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_translatedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatedpost",
            name="translated_description",
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="main.post",
                    ),
                ),
            ],
        ),
    ]
