# Generated by Django 4.2.2 on 2023-09-30 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_translatedpost_translated_description_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="post",
            name="timestamp_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="timestamp_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
